In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
A = np.random.randn(10)
A

array([ 0.35915395, -0.28321433, -1.76862302,  0.2210265 ,  0.11276658,
       -0.61173822,  0.64274753,  1.16485707, -2.19867062, -0.99306604])

In [5]:
rng = np.random.default_rng()
B = rng.standard_normal(10)
B

array([-0.80727318,  1.23756569,  0.97217081, -1.47728566,  0.87111966,
        0.54343085,  0.72057914, -2.42214166, -0.04266157, -0.8999302 ])

In [6]:
np.add(A, B)

array([-0.44811923,  0.95435137, -0.79645221, -1.25625916,  0.98388624,
       -0.06830737,  1.36332667, -1.25728459, -2.24133219, -1.89299625])

In [7]:
np.maximum(A, B)

array([ 0.35915395,  1.23756569,  0.97217081,  0.2210265 ,  0.87111966,
        0.54343085,  0.72057914,  1.16485707, -0.04266157, -0.8999302 ])