In [2]:
import numpy as np

In [3]:
my_list1 = [1, 2, 3, 4]

In [5]:
my_array1 = np.array(my_list1)

In [6]:
my_array1

array([1, 2, 3, 4])

In [7]:
my_list2 = [11,22,33,44]

In [8]:
my_lists = [my_list1, my_list2]

In [9]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [10]:
my_array2 = np.array(my_lists)

In [11]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int64')

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
my_zeros = np.zeros(5)

In [16]:
my_zeros.dtype

dtype('float64')